name: uBO Lite beta

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write # for creating release
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: recursive
      - name: Locate uBO repo
        run: |
          UBOL_REPO_DIR=$(pwd)
          UBLOCK_REPO_DIR="$UBOL_REPO_DIR/uBlock"
          echo "UBLOCK_REPO_DIR=$UBLOCK_REPO_DIR" >> $GITHUB_ENV
      # Version, time-based
      - name: Create unique time-based version
        run: |
          TAGNAME=$(date -u "+%Y").$(date -u "+%-m*100+%-d" | bc).$(date -u "+%H*100+%M" | bc)
          echo "TAGNAME=$TAGNAME" >> $GITHUB_ENV
          echo "Version: $TAGNAME"
      # Chromium
      - name: Build Chromium uBOLite beta
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UBOL_REPO_DIR=$(pwd)
          cd $UBLOCK_REPO_DIR
          tools/make-mv3.sh chromium ${{ env.TAGNAME }}
          cd - > /dev/null
          mv ${{ env.UBLOCK_REPO_DIR }}/dist/build/uBOLite_${{ env.TAGNAME }}.chromium.zip \
             ${{ env.UBLOCK_REPO_DIR }}/dist/build/uBOLite.beta.chromium.zip
      # Edge
      - name: Build Edge uBOLite beta
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UBOL_REPO_DIR=$(pwd)
          cd $UBLOCK_REPO_DIR
          tools/make-mv3.sh edge ${{ env.TAGNAME }}
          cd - > /dev/null
          mv ${{ env.UBLOCK_REPO_DIR }}/dist/build/uBOLite_${{ env.TAGNAME }}.edge.zip \
             ${{ env.UBLOCK_REPO_DIR }}/dist/build/uBOLite.beta.edge.zip
      # Firefox
      - name: Build Firefox uBOLite beta
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UBOL_REPO_DIR=$(pwd)
          cd $UBLOCK_REPO_DIR
          tools/make-mv3.sh firefox ${{ env.TAGNAME }}
          cd - > /dev/null
          mv ${{ env.UBLOCK_REPO_DIR }}/dist/build/uBOLite_${{ env.TAGNAME }}.firefox.xpi \
             ${{ env.UBLOCK_REPO_DIR }}/dist/build/uBOLite.beta.firefox.xpi
      # Safari
      - name: Build Safari uBOLite beta
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UBOL_REPO_DIR=$(pwd)
          cd $UBLOCK_REPO_DIR
          tools/make-mv3.sh safari ${{ env.TAGNAME }}
          cd - > /dev/null
          mv ${{ env.UBLOCK_REPO_DIR }}/dist/build/uBOLite_${{ env.TAGNAME }}.safari.zip \
             ${{ env.UBLOCK_REPO_DIR }}/dist/build/uBOLite.beta.safari.zip
      - name: Create GitHub beta release
        id: create_beta_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAGNAME }}-beta
          name: ${{ env.TAGNAME }}-beta
          prerelease: true
          body: |
            **uBO Lite** (uBOL), an [MV3 API-based](https://developer.chrome.com/docs/extensions/mv3/intro/) content blocker.
            
            - [Synopsis](https://github.com/uBlockOrigin/uBOL-issues#readme)
            - [Documentation](https://github.com/uBlockOrigin/uBOL-home/wiki)
            
            ## Release notes
            
            - Updated filter lists
            
            # Installation
            
            - Firefox: Click [uBOLite ${{ env.TAGNAME }}-beta](https://github.com/uBlockOrigin/uBOL-home/releases/download/${{ env.TAGNAME }}-beta/uBOLite.beta.firefox.signed.xpi)
            
          files: |
            ${{ env.UBLOCK_REPO_DIR }}/dist/build/uBOLite.beta.chromium.zip
            ${{ env.UBLOCK_REPO_DIR }}/dist/build/uBOLite.beta.edge.zip
            ${{ env.UBLOCK_REPO_DIR }}/dist/build/uBOLite.beta.firefox.xpi
            ${{ env.UBLOCK_REPO_DIR }}/dist/build/uBOLite.beta.safari.zip
